services:
  qbupload:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      QB_URL: "${QB_URL}"
      QB_USER: "${QB_USER}"
      QB_PASS: "${QB_PASS}"
      WATCH_DIR: "/downloads"
    volumes:
      - "${WATCH_DIR}:/downloads"
